### ISSUE TITLE
The Booking option ... does it work?

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#239]
Hi mate,

The "Booking" option doesn't work properly.

I think the reasons are :  
![creenshot11](https://user-images.githubusercontent.com/48275749/55906601-056bd900-5bab-11e9-8b37-0c8ba3be3a05.jpg)

When selecting the car,.... the option creates a slot in the file "entry_list.ini"
but this file must be without slots (only empty)
![creenshot12](https://user-images.githubusercontent.com/48275749/55907002-f9cce200-5bab-11e9-926b-1d64c0b489e4.jpg)
![creenshot11](https://user-images.githubusercontent.com/48275749/55907011-ffc2c300-5bab-11e9-8baa-5c83ea95a02e.jpg)

however ... the selected car must be declared in the file "server_cfg.ini

![creenshot11](https://user-images.githubusercontent.com/48275749/55907176-62b45a00-5bac-11e9-8f6c-57288a358f19.jpg)

I hope I was clear. 
Sorry for my bad english

Thanks in advance

**Comment by cj123** [comment]
Hi Luis, thanks for reporting this. I've taken a look and I should be able to get a fix for this in with our next release :)

**Comment by Hecrer** [comment]
Fixed in 1.2

**Comment by luismercury** [comment]
Hi Callum and Hecrer,

The problem still persists.
Basically in Championships mode.
*********************************************************

In custom race mode it works fine. 
and it allows me to define how many drivers can enter the booking mode.
in the example, it proposes the total of pits available in the track (24)
![creenshot11](https://user-images.githubusercontent.com/48275749/55990197-77acee00-5c7d-11e9-8258-aa934eead7c7.jpg)

however this option isn't available in "Championships mode"
![creenshot12](https://user-images.githubusercontent.com/48275749/55990950-6cf35880-5c7f-11e9-8938-6fda54af30de.jpg)

and another collateral problem is that if we want to use "mode booking" in "mode "START PRACTICE EVENT" it's created with 0 slots
![creenshot12](https://user-images.githubusercontent.com/48275749/55991401-9365c380-5c80-11e9-9c25-dcb61e0e5582.jpg)

remember in "booking mode" the file "entry_list.ini" must be empty.

Regards

**Comment by cj123** [comment]
Hi Luis,

Booking mode is available on open championships, but not closed championships.

It doesn't make sense on closed championships where the entrylist must be preconfigured.

Thanks

**Comment by luismercury** [comment]
Yes ... I understand.

I have selected Open Championship = On

I mean, my tests were done with this option in ON  (Open Championship = On)

**Comment by cj123** [comment]
I'll look into it :)

**Comment by cj123** [comment]
Bundling this in with #271, hope to fix in v1.3.1
